name: 京豆签到

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
jobs:
  submit-and-send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: node ./submit/jindou-actions.js ${{secrets.JD_PT_KEY}} ${{secrets.JD_PT_PIN}}