name: juejin submit

on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  submit-send-email:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: | 
          cd submit
          npm install
      - name: run juejin submit
        run: |
          node juejin-actions.js ${{secrets.JUEJIN_COOKIE}} ${{secrets.QQ_EMAIL_PASS}}
          cd -